/* Auto-generated by genmsg_cpp for file /home/amos/amos/hardware/base_msgs/msg/motorOdom.msg */
#ifndef BASE_MSGS_MESSAGE_MOTORODOM_H
#define BASE_MSGS_MESSAGE_MOTORODOM_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace base_msgs
{
template <class ContainerAllocator>
struct motorOdom_ {
  typedef motorOdom_<ContainerAllocator> Type;

  motorOdom_()
  : left(0.0)
  , right(0.0)
  , leftTime(0.0)
  , rightTime(0.0)
  {
  }

  motorOdom_(const ContainerAllocator& _alloc)
  : left(0.0)
  , right(0.0)
  , leftTime(0.0)
  , rightTime(0.0)
  {
  }

  typedef float _left_type;
  float left;

  typedef float _right_type;
  float right;

  typedef float _leftTime_type;
  float leftTime;

  typedef float _rightTime_type;
  float rightTime;


  typedef boost::shared_ptr< ::base_msgs::motorOdom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_msgs::motorOdom_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct motorOdom
typedef  ::base_msgs::motorOdom_<std::allocator<void> > motorOdom;

typedef boost::shared_ptr< ::base_msgs::motorOdom> motorOdomPtr;
typedef boost::shared_ptr< ::base_msgs::motorOdom const> motorOdomConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::base_msgs::motorOdom_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::base_msgs::motorOdom_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace base_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::base_msgs::motorOdom_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::base_msgs::motorOdom_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::base_msgs::motorOdom_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3adcce373d2857cd80a29bd688b1f0d2";
  }

  static const char* value(const  ::base_msgs::motorOdom_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3adcce373d2857cdULL;
  static const uint64_t static_value2 = 0x80a29bd688b1f0d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::base_msgs::motorOdom_<ContainerAllocator> > {
  static const char* value() 
  {
    return "base_msgs/motorOdom";
  }

  static const char* value(const  ::base_msgs::motorOdom_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::base_msgs::motorOdom_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 left\n\
float32 right\n\
float32 leftTime\n\
float32 rightTime\n\
\n\
";
  }

  static const char* value(const  ::base_msgs::motorOdom_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::base_msgs::motorOdom_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::base_msgs::motorOdom_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.left);
    stream.next(m.right);
    stream.next(m.leftTime);
    stream.next(m.rightTime);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct motorOdom_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_msgs::motorOdom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::base_msgs::motorOdom_<ContainerAllocator> & v) 
  {
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
    s << indent << "leftTime: ";
    Printer<float>::stream(s, indent + "  ", v.leftTime);
    s << indent << "rightTime: ";
    Printer<float>::stream(s, indent + "  ", v.rightTime);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BASE_MSGS_MESSAGE_MOTORODOM_H

