/* Auto-generated by genmsg_cpp for file /home/amos/amos/hardware/base_msgs/msg/motorRst.msg */
#ifndef BASE_MSGS_MESSAGE_MOTORRST_H
#define BASE_MSGS_MESSAGE_MOTORRST_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace base_msgs
{
template <class ContainerAllocator>
struct motorRst_ {
  typedef motorRst_<ContainerAllocator> Type;

  motorRst_()
  {
  }

  motorRst_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::base_msgs::motorRst_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_msgs::motorRst_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct motorRst
typedef  ::base_msgs::motorRst_<std::allocator<void> > motorRst;

typedef boost::shared_ptr< ::base_msgs::motorRst> motorRstPtr;
typedef boost::shared_ptr< ::base_msgs::motorRst const> motorRstConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::base_msgs::motorRst_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::base_msgs::motorRst_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace base_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::base_msgs::motorRst_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::base_msgs::motorRst_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::base_msgs::motorRst_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::base_msgs::motorRst_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::base_msgs::motorRst_<ContainerAllocator> > {
  static const char* value() 
  {
    return "base_msgs/motorRst";
  }

  static const char* value(const  ::base_msgs::motorRst_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::base_msgs::motorRst_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::base_msgs::motorRst_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::base_msgs::motorRst_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::base_msgs::motorRst_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct motorRst_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_msgs::motorRst_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::base_msgs::motorRst_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // BASE_MSGS_MESSAGE_MOTORRST_H

