/* Auto-generated by genmsg_cpp for file /home/amos/amos/hardware/base_msgs/msg/setPid.msg */
#ifndef BASE_MSGS_MESSAGE_SETPID_H
#define BASE_MSGS_MESSAGE_SETPID_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace base_msgs
{
template <class ContainerAllocator>
struct setPid_ {
  typedef setPid_<ContainerAllocator> Type;

  setPid_()
  : p(0.0)
  , i(0.0)
  , d(0.0)
  {
  }

  setPid_(const ContainerAllocator& _alloc)
  : p(0.0)
  , i(0.0)
  , d(0.0)
  {
  }

  typedef float _p_type;
  float p;

  typedef float _i_type;
  float i;

  typedef float _d_type;
  float d;


  typedef boost::shared_ptr< ::base_msgs::setPid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_msgs::setPid_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct setPid
typedef  ::base_msgs::setPid_<std::allocator<void> > setPid;

typedef boost::shared_ptr< ::base_msgs::setPid> setPidPtr;
typedef boost::shared_ptr< ::base_msgs::setPid const> setPidConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::base_msgs::setPid_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::base_msgs::setPid_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace base_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::base_msgs::setPid_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::base_msgs::setPid_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::base_msgs::setPid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cccd09188ee638c943ed6be95f1812c9";
  }

  static const char* value(const  ::base_msgs::setPid_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcccd09188ee638c9ULL;
  static const uint64_t static_value2 = 0x43ed6be95f1812c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::base_msgs::setPid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "base_msgs/setPid";
  }

  static const char* value(const  ::base_msgs::setPid_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::base_msgs::setPid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 p\n\
float32 i\n\
float32 d\n\
\n\
";
  }

  static const char* value(const  ::base_msgs::setPid_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::base_msgs::setPid_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::base_msgs::setPid_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.p);
    stream.next(m.i);
    stream.next(m.d);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct setPid_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_msgs::setPid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::base_msgs::setPid_<ContainerAllocator> & v) 
  {
    s << indent << "p: ";
    Printer<float>::stream(s, indent + "  ", v.p);
    s << indent << "i: ";
    Printer<float>::stream(s, indent + "  ", v.i);
    s << indent << "d: ";
    Printer<float>::stream(s, indent + "  ", v.d);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BASE_MSGS_MESSAGE_SETPID_H

