ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = /usr/local
AVR_TOOLS_DIR = /usr

ARDUINO_LIBS = Wire Wire/utility
BOARD_TAG = atmega328
ARDUINO_PORT = /dev/compass

AVRDUDE_ARD_PROGRAMMER=arduino

SRC_DIRS=src src/ros_lib src/ros_lib/ros

include /usr/share/arduino/Arduino.mk

