/* Auto-generated by genmsg_cpp for file /home/amos/amosRos/hardware/compass_msg/msg/Compass.msg */
#ifndef COMPASS_MSG_MESSAGE_COMPASS_H
#define COMPASS_MSG_MESSAGE_COMPASS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace compass_msg
{
template <class ContainerAllocator>
struct Compass_ {
  typedef Compass_<ContainerAllocator> Type;

  Compass_()
  : heading(0.0)
  {
  }

  Compass_(const ContainerAllocator& _alloc)
  : heading(0.0)
  {
  }

  typedef float _heading_type;
  float heading;


  typedef boost::shared_ptr< ::compass_msg::Compass_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::compass_msg::Compass_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Compass
typedef  ::compass_msg::Compass_<std::allocator<void> > Compass;

typedef boost::shared_ptr< ::compass_msg::Compass> CompassPtr;
typedef boost::shared_ptr< ::compass_msg::Compass const> CompassConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::compass_msg::Compass_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::compass_msg::Compass_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace compass_msg

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::compass_msg::Compass_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::compass_msg::Compass_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::compass_msg::Compass_<ContainerAllocator> > {
  static const char* value() 
  {
    return "22eeef76ab4645786a2d92bcfbc4c574";
  }

  static const char* value(const  ::compass_msg::Compass_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x22eeef76ab464578ULL;
  static const uint64_t static_value2 = 0x6a2d92bcfbc4c574ULL;
};

template<class ContainerAllocator>
struct DataType< ::compass_msg::Compass_<ContainerAllocator> > {
  static const char* value() 
  {
    return "compass_msg/Compass";
  }

  static const char* value(const  ::compass_msg::Compass_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::compass_msg::Compass_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 heading\n\
\n\
";
  }

  static const char* value(const  ::compass_msg::Compass_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::compass_msg::Compass_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::compass_msg::Compass_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.heading);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Compass_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::compass_msg::Compass_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::compass_msg::Compass_<ContainerAllocator> & v) 
  {
    s << indent << "heading: ";
    Printer<float>::stream(s, indent + "  ", v.heading);
  }
};


} // namespace message_operations
} // namespace ros

#endif // COMPASS_MSG_MESSAGE_COMPASS_H

